import os
import sys
import re
import json
import time
import operator
import sqlite3
import yfinance as yf
import pandas as pd
import pandas_ta as ta  # For RSI, ATR, and EMA indicators
from dotenv import load_dotenv
from google import genai
from google.genai import types

# Force UTF-8 encoding on Windows terminal stdout/stderr
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found in environment or .env file.")

client = genai.Client(api_key=GEMINI_API_KEY)
DB_FILE = "trade_memory.db"
NOTES_FILE = "strategy_notes.md"

# Map string operators to Python operator functions
OPERATORS = {
    ">": operator.gt,
    "<": operator.lt,
    ">=": operator.ge,
    "<=": operator.le,
    "==": operator.eq,
}

# ==========================================
# DATABASE & LOGGING INITIALIZATION
# ==========================================
def init_db():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            round INTEGER,
            timestamp TEXT,
            symbol TEXT,
            action TEXT,
            entry_price REAL,
            exit_price REAL,
            pnl REAL,
            status TEXT,
            gemini_lesson TEXT
        )
    """)
    cursor.execute("PRAGMA table_info(trades)")
    columns = [col[1] for col in cursor.fetchall()]
    if "round" not in columns:
        cursor.execute("ALTER TABLE trades ADD COLUMN round INTEGER DEFAULT 1")
    conn.commit()
    conn.close()

def log_trade(round_num, timestamp, symbol, action, entry, exit_p, pnl, status):
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO trades (round, timestamp, symbol, action, entry_price, exit_price, pnl, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (round_num, str(timestamp), symbol, action, entry, exit_p, pnl, status))
    trade_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return trade_id

# ==========================================
# DYNAMIC RULE ENGINE (PARSER & EVALUATOR)
# ==========================================
def load_guardrails_from_notes(notes_file=NOTES_FILE):
    """
    Scans strategy_notes.md for JSON rule blocks generated by Gemini
    and converts them into active runtime guardrails.
    """
    if not os.path.exists(notes_file):
        return []

    with open(notes_file, "r", encoding="utf-8") as f:
        content = f.read()

    # Regex matches all ```json ... ``` blocks in strategy_notes.md
    json_blocks = re.findall(r"```json\s*(\{.*?\})\s*```", content, re.DOTALL)
    
    guardrails = []
    for block in json_blocks:
        try:
            rule_data = json.loads(block)
            if isinstance(rule_data, dict) and "rules" in rule_data:
                guardrails.extend(rule_data["rules"])
            elif isinstance(rule_data, list):
                guardrails.extend(rule_data)
            elif isinstance(rule_data, dict):
                guardrails.append(rule_data)
        except json.JSONDecodeError:
            continue

    return guardrails

def evaluate_dynamic_guardrails(row, guardrails):
    """
    Evaluates market indicators (row) against all rules parsed from strategy_notes.md.
    Executes automatically without modifying Python code!
    """
    # 1. Base Strategy Filters (Hardcoded Core Rules)
    if float(row['close']) < float(row['ema50']):
        return False, f"Base Strategy Rejection: Price (${row['close']:.2f}) < 50 EMA (${row['ema50']:.2f})"
    if float(row['rsi14']) < 50:
        return False, f"Base Strategy Rejection: RSI ({row['rsi14']:.1f}) < 50"

    # 2. Gemini Learned Guardrails (Parsed dynamically from Markdown)
    for rule in guardrails:
        field = rule.get("field")
        op_str = rule.get("operator")
        threshold = rule.get("threshold")

        if not field or not op_str or threshold is None:
            continue

        if field in row:
            val = float(row[field])
            op_func = OPERATORS.get(op_str)

            if op_func:
                if not op_func(val, float(threshold)):
                    reason = f"Learned Guardrail Triggered: {field} ({val:.2f}) {op_str} {threshold} failed"
                    return False, reason

    return True, ""

# ==========================================
# GEMINI SELF-UPGRADE LOOP
# ==========================================
def analyze_round_failures_and_upgrade(round_num, total_trades, win_rate):
    """
    Reads loss logs and prior strategy notes, sends them to Gemini, 
    and appends structured JSON rules directly to strategy_notes.md.
    """
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT timestamp, symbol, entry_price, exit_price, pnl, status 
        FROM trades WHERE round = ? AND status IN ('LOSS', 'STOP_LOSS_HIT')
    """, (round_num,))
    losses = cursor.fetchall()
    conn.close()

    if not losses:
        return

    # Load audit history directly from strategy_notes.md to provide full context
    previous_notes = ""
    if os.path.exists(NOTES_FILE):
        with open(NOTES_FILE, "r", encoding="utf-8") as f:
            previous_notes = f.read()

    loss_summary = []
    for l in losses[:5]:
        loss_summary.append({
            "date": l[0],
            "entry": l[2],
            "exit": l[3],
            "pnl": l[4],
            "status": l[5]
        })

    prompt = f"""
    You are an automated quantitative strategy optimizer reviewing Round {round_num}.
    Win rate achieved: {win_rate:.2f}% across {total_trades} trades. Target Win Rate: >= 60%.

    === PREVIOUS STRATEGY AUDIT NOTES ===
    {previous_notes}

    === RECENT LOSING TRADES (ROUND {round_num}) ===
    {json.dumps(loss_summary, indent=2)}

    Identify why trades lost and output quantitative entry guardrails.
    Available features in dataset: ['close', 'ema50', 'rsi14', 'atr14']

    Return STRICTLY a JSON block enclosed in ```json ``` containing an array of rules:
    ```json
    {{
      "rules": [
        {{
          "field": "rsi14",
          "operator": ">=",
          "threshold": 55,
          "description": "Require stronger entry momentum (RSI >= 55)"
        }}
      ]
    }}
    ```
    """
    
    INITIAL_PACING_DELAY = 60 
    RETRY_DELAYS = [60, 120, 180]

    print(f"\n  |-- Waiting {INITIAL_PACING_DELAY}s before API analysis...")
    time.sleep(INITIAL_PACING_DELAY)

    for attempt, wait_time in enumerate(RETRY_DELAYS, 1):
        try:
            print(f"  |-- Sending loss log to gemini-3.6-flash (Attempt {attempt}/{len(RETRY_DELAYS)})...")
            
            response = client.models.generate_content(
                model="gemini-3.6-flash",
                contents=prompt,
                config=types.GenerateContentConfig(response_mime_type="application/json")
            )
            
            rule_json = response.text

            # Persist raw lesson JSON to SQLite DB
            conn = sqlite3.connect(DB_FILE)
            cursor = conn.cursor()
            cursor.execute("UPDATE trades SET gemini_lesson = ? WHERE round = ? AND status IN ('LOSS', 'STOP_LOSS_HIT')", (rule_json, round_num))
            conn.commit()
            conn.close()

            # Append readable audit log + runnable JSON rules directly to strategy_notes.md
            with open(NOTES_FILE, "a", encoding="utf-8") as f:
                f.write(f"\n## Iteration Round {round_num} Analysis\n")
                f.write(f"- **Win Rate Achieved**: {win_rate:.2f}%\n")
                f.write(f"- **Total Trades**: {total_trades}\n")
                f.write(f"- **Generated Rule Set**:\n```json\n{rule_json}\n```\n\n")

            print(f"  |-- [GEMINI SELF-UPGRADE SUCCESS]: Appended new rules to {NOTES_FILE}.")
            break

        except Exception as e:
            error_str = str(e)
            if "429" in error_str or "RESOURCE_EXHAUSTED" in error_str:
                print(f"  |-- [429 Quota Encountered]. Backing off for {wait_time}s...")
                time.sleep(wait_time)
            else:
                print(f"  |-- [API Request Error]: {e}")
                break

# ==========================================
# MAIN BACKTEST ENGINE
# ==========================================
def run_iterative_backtest(symbol="BTC-USD", period="2y", max_rounds=3):
    init_db()
    
    if not os.path.exists(NOTES_FILE):
        with open(NOTES_FILE, "w", encoding="utf-8") as f:
            f.write("# Autonomous Agent - Strategy Upgrade Notes\n")

    print(f"\n--- Fetching Market Data for {symbol} ({period}) ---")
    df = yf.download(symbol, period=period, interval="1d")
    if df.empty:
        print("Error: Could not retrieve price data from Yahoo Finance.")
        return

    # Normalize column headers
    df.columns = [col[0].lower() if isinstance(col, tuple) else col.lower() for col in df.columns]

    # Calculate Technical Indicators
    df['ema50'] = df['close'].ewm(span=50, adjust=False).mean()
    df['high_20'] = df['high'].shift(1).rolling(window=20).max()
    
    # Calculate RSI (14)
    delta = df['close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    df['rsi14'] = 100 - (100 / (1 + rs))
    
    # Calculate ATR (14)
    high_low = df['high'] - df['low']
    high_close = (df['high'] - df['close'].shift()).abs()
    low_close = (df['low'] - df['close'].shift()).abs()
    tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
    df['atr14'] = tr.rolling(window=14).mean()

    for round_num in range(1, max_rounds + 1):
        # Read strategy_notes.md dynamically at start of every round
        active_guardrails = load_guardrails_from_notes()
        
        print(f"\n==========================================")
        print(f" STARTING BACKTEST ROUND {round_num} / {max_rounds}")
        print(f" Active Guardrails Loaded from {NOTES_FILE}: {len(active_guardrails)}")
        print(f"==========================================")

        total_trades = 0
        wins = 0
        losses = 0

        for i in range(50, len(df) - 5):
            row = df.iloc[i]
            prev_row = df.iloc[i-1]
            timestamp = df.index[i]

            # Entry Trigger: 20-Day High Breakout
            if prev_row['close'] <= prev_row['high_20'] and row['close'] > row['high_20']:
                
                # Dynamic check against all learned guardrails
                allowed, reason = evaluate_dynamic_guardrails(row, active_guardrails)
                
                if not allowed:
                    print(f"[REJECTED] Date: {timestamp.date()} | Reason: {reason}")
                    continue

                total_trades += 1
                entry_price = float(row['close'])
                atr = float(row['atr14'])

                # Dynamic Volatility Stop-Loss (1.5x ATR)
                stop_loss = entry_price - (1.5 * atr)
                future_low = min(df.iloc[i+1]['low'], df.iloc[i+2]['low'], df.iloc[i+3]['low'])

                if future_low <= stop_loss:
                    exit_price = stop_loss
                    status = "STOP_LOSS_HIT"
                    losses += 1
                else:
                    exit_price = float(df.iloc[i+3]['close'])
                    status = "WIN" if exit_price > entry_price else "LOSS"
                    if status == "WIN":
                        wins += 1
                    else:
                        losses += 1

                pnl = exit_price - entry_price
                print(f"[EXECUTED] Date: {timestamp.date()} | Entry: ${entry_price:.2f} | Exit: ${exit_price:.2f} | Status: {status}")
                log_trade(round_num, timestamp.date(), symbol, "BUY", entry_price, exit_price, pnl, status)

        win_rate = (wins / total_trades * 100) if total_trades > 0 else 0
        print(f"\n--- ROUND {round_num} SUMMARY ---")
        print(f"Total Trades: {total_trades}")
        print(f"Wins: {wins} | Losses: {losses}")
        print(f"Win Rate: {win_rate:.2f}%")

        if win_rate >= 60.0:
            print(f"\n[TARGET ACHIEVED] Win rate is {win_rate:.2f}% (>= 60%). Strategy optimization complete.")
            break
        else:
            print(f"\n[TARGET UNMET] Win rate {win_rate:.2f}% < 60%. Invoking Gemini upgrade loop...")
            analyze_round_failures_and_upgrade(round_num, total_trades, win_rate)

if __name__ == "__main__":
    run_iterative_backtest(symbol="BTC-USD", period="2y", max_rounds=3)